#PyTorch Basics

## Importing PyTorch and needed libraries



In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


## Introduction to Tensors
https://pytorch.org/docs/stable/index.html

#### Creating Tensors

*PyTorch tensors are created using `torch.tensor()`*  
https://pytorch.org/docs/stable/tensors.html

##### Scalars
*Scalars are commonly used in PyTorch to represent single numerical values, such as loss or accuracy metrics.*


In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

Scalar has no dimension

In [6]:
scalar.ndim

0

Get tensor back as Python int

In [7]:
scalar.item()

7

##### Vectors
*In PyTorch, a vector is a one-dimensional tensor that contains a sequence of numerical values.*

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

Vector has one dimension

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

##### Matrix

In [11]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Matrix has two dimensions

In [12]:
MATRIX.ndim

2

In [13]:
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [14]:
MATRIX.shape

torch.Size([2, 2])

##### Tensor
*Tensors are a fundamental data structure in many deep learning frameworks, such as TensorFlow and PyTorch, and they can be used to represent a wide range of data, including images, audio, text, and numerical data.*

In [15]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9,]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

Number of dimentions of our tensor

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
# dim=0
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

#### Random Tensors
*Random tensors ar important because the way many neural networks learn is that start with tensor full of random numbers and then adjust those random numbers to beter represent the data*

`Start with random numbers -> Look at data -> Update random numbers
-> Look at data -> Update random numbers`

Random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=torch+rand#torch.rand


In [19]:
# create random tensor (1, 3, 4)

random_tensor = torch.rand(1, 3, 4)
# random_tensor = torch.rand(size=(1, 3, 4))
random_tensor

tensor([[[0.8981, 0.8513, 0.0674, 0.8811],
         [0.4724, 0.9847, 0.7760, 0.2327],
         [0.6336, 0.0649, 0.3282, 0.0113]]])

In [20]:
random_tensor.ndim

3

In [21]:
random_tensor.dtype

torch.float32

In [22]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color chanels (R,G,B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#### Zeros and ones

In [23]:
# create tensor full of all zeros

zeros_tensor = torch.zeros(3, 4)
zeros_tensor 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# create tensor full of all ones

ones_tensor = torch.ones(3, 4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range() and get deprecated message, use torch.arange() insted

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Creating tensors like

ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of 3 big errors you'll run into with PyTorch and deep learning.

Datatype - https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype
Device - https://pytorch.org/docs/stable/tensor_attributes.html#torch.device



In [27]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,            # what datatype is the tensor (defeault: float 32) 
                               device=None,           # what device is your tensor on       
                               requires_grad=False)   # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_64_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float64)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [31]:
bool_tensor = torch.tensor([1,0,1], dtype=torch.bool)
bool_tensor, bool_tensor.dtype

(tensor([ True, False,  True]), torch.bool)

## Getting information from tensor

1.   Tensors not right datatype: *to get datatype of a tensor use `tensor.dtype`*
2.   Tensor not right shape (e.g. during matrix multiplication): *to get shape of a tensor use `tensor.shape`*
3.   Tensor not on the right device: *to get divice from a tensor use `tensor.divice`*



In [32]:
# Create a tensor 
tensor = torch.rand(2,3,4).type(torch.float64)

In [33]:
# Finding out details about tensor

print(tensor)
print('\nDetails of tensor:')
print(f'\t datatype: {tensor.dtype}')
print(f'\t shape: {tensor.shape}')
print(f'\t device: {tensor.device}')

tensor([[[0.5490, 0.5929, 0.6534, 0.3850],
         [0.5180, 0.9458, 0.0139, 0.2307],
         [0.9572, 0.3100, 0.1684, 0.0194]],

        [[0.6471, 0.7717, 0.3582, 0.1716],
         [0.8819, 0.4022, 0.6928, 0.2885],
         [0.5948, 0.8987, 0.3045, 0.9817]]], dtype=torch.float64)

Details of tensor:
	 datatype: torch.float64
	 shape: torch.Size([2, 3, 4])
	 device: cpu


## Manipulating tensors (tensors operations)

Tensors operations:
* addition
* subtraction
* multiplication (element-wise)
* dvision
* matrix multiplication







### Basic operations on tensors

In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Substract 10 
tensor - 10

tensor([-9, -8, -7])

In [37]:
# We can use PyTorch in-build fonctions
multiplied_tensor = torch.mul(tensor, 10)
tensor_with_added_10 = torch.add(tensor, 10)

multiplied_tensor, tensor_with_added_10

(tensor([10, 20, 30]), tensor([11, 12, 13]))

### Matrix multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product): *use `torch.matmul()` or `torch.mm()` or `@`*
    
    https://pytorch.org/docs/stable/generated/torch.mm.html?highlight=torch+mm#torch.mm


There are two matrix multiplication rules that must be followed:
1. The **inner dimension** must match:
  * `(3, 2) @ (3, 2)` won't work

    `RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)`
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
  * `(3, 2) @ (2, 3) -> (3, 3)`

In [38]:
# Element wise multiplication 
print(tensor, '*', tensor)
print(tensor * tensor) # [(1*1), (2*2), (3*3)]


tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [39]:
# Matrix multiplication
torch.matmul(tensor, tensor) # 1*1 + 2*2 + 3*3 = 14 

tensor(14)

## Most common errors in deep learning: 
1.   Tensors not right datatype
2.   Tensor not right shape (e.g. during matrix multiplication)
3.   Tensor not on the right device

### Shape error

In [40]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2], 
                         [3, 4], 
                         [5, 6]])
tensor_B = torch.tensor([[7, 10], 
                         [8, 11], 
                         [9, 12]])

In [41]:
# torch.mm(tensor_A, tensor_B)

In [42]:
# It doesn't work because 
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

**Note:** To fix our tensor shape issues, we can manipulate shape of one of our tensors using `transpose`.

In [43]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [44]:
# It will works because we have two matrix multiplication with shapes (3, 2)x(2, 3)
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc. (tensor agregation)

In [45]:
# Create a tensor 
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [46]:
# Finding the min 
torch.min(x), x.min()

(tensor(0), tensor(0))

In [47]:
# Finding the max 
torch.max(x), x.max()

(tensor(90), tensor(90))

In [48]:
# Finding the mean - note: the torch.mean() dunction requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [49]:
# Finding the sum 
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [50]:
# Finding the standard deviation - note: the torch.std() dunction requires a tensor of float32 datatype to work
torch.std(x.type(torch.float32)), x.type(torch.float32).std()

(tensor(30.2765), tensor(30.2765))

## Finding the positional of min and max

In [51]:
# Find the position in tensor that has the minimum/maximum value with argmin() -> returns index of position
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping (`reshape()`) - reshapes an input tensor to a define shape
  * **note:** `our new shape has to be equal as previous`
* View (`view()`) - return a view od an input tensor of certain shape but keep yhe same memory as the orginal tensor
* Stacking (`stack()`)- comnibe multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze (`squeeze()`) - removes all `1` dimension from a tensor
* Unsqueeze (`unsqueeze(dim=1)`) - add `1` dimension to a target tensor 
* Permute (`permute()`) - return a view of the input with dimensions permuted (swapped) in a certain way

In [52]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
# Add an extra dimension - note: our new shape has to be equal as previous 1*9=9
x_reshaped = x.reshape(1, 9)
print(x_reshaped, x_reshaped.shape)

# We can also make (9, 1) because 9*1=9 
x_reshaped_2 = x.reshape(9, 1) 
print(x_reshaped_2, x_reshaped_2.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])


In [54]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
# Changing z changes x (because a view of a tensor shares the same memory as the orginal input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
# Squeezing a tensor using
## torch.squeeze()- removes all single dimensions from a target tensor
x_squeezed = torch.squeeze(x)
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
# For better visualization of squeezing a tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [59]:
# Unsqueeze a tensor
## torch.unsqueeze()- adds a single dimensions to a target tensor ta s specific dim (dimension)
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# For better visualization of unsqueezing a tensor
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [61]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_orginal = torch.rand(size=(224, 224, 3)) # (height, width, color_chanels)- common for image data 

# Permute the orginal tensor to rearrange the axis (or dim) order
x_permured = x_orginal.permute(2, 0, 1) # shifts axis order -> (color_chanels, height, width)

print(f'Previous shape: {x_orginal.shape}')
print(f'New shape: {x_permured.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensor)


In [62]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
# Indexing the outer bracket of our tensor (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
# Indexing the middle bracket (dim=1)
x[0][0]
x[0, 0] # works the same!

tensor([1, 2, 3])

In [65]:
# Indexing the inner bracket (last dim)
x[0][2][2]

tensor(9)

Our tensor has shape [**1**, 3, 3], in our dim=0 we have **1**, but in indexing `x[0][2][2]` in the first bracket we can pass only 0 (it may be confusing)

In [66]:
# We can use also ':' to select 'all' of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [67]:
# More complex example:
# Get all values of 0th and 1st dimensions but only 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

## PyTorch tensors and NumPy

* Data in NumPy to PyTorch tensor -> `torch.from_numpy(ndarray)`
* Data in PyTorch tensor to NumPy -> `torch.Tensor.numpy)_`

In [68]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0) # numpy has default datatyple float 64
tensor = torch.from_numpy(array) # WARNING: during converting from numpy -> pytorch, pytorch takes numpy's default datatype 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
# Changing the values of array doesn't change value in tensor
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [70]:
# Tensor to NumPy array
tensor = torch.ones(7)
array = tensor.numpy() # new array keeps datatype of the tensor
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [71]:
# Changing the tensor's values doesn't change value in tensor
tensor = tensor + 1
tensor, array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Note:** PyTorch tensor and NumPy array don't share the memory

## Reproducbility (trying to take the random out of random) 
 
In short how a neural networks learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again..`

To reduce randomness in neural networks and PyTorch comes to the concept of a **random seed**.

* https://pytorch.org/docs/stable/random.html?highlight=random+seed#torch.random.seed

* https://en.wikipedia.org/wiki/Random_seed

In [72]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.4522, 0.5294, 0.1206, 0.0560],
         [0.5200, 0.3209, 0.7139, 0.9750],
         [0.7991, 0.3406, 0.0876, 0.2256]]),
 tensor([[0.5777, 0.3818, 0.3588, 0.3770],
         [0.5680, 0.3249, 0.7972, 0.4588],
         [0.1908, 0.5076, 0.7382, 0.5937]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [73]:
# Create two random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42 

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D, random_tensor_C==random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

**Note:** *using `torch.manual_seed(RANDOM_SEED)` -> remeber it works only for 
one block of code, so we need to use it each time*

##  Running tensors and PyTorch objects on the GPUs (and making faster computations)


### Getting a GPU:
In Google Colab:

`Runtime -> Change runtime type -> Hardware accelerator -> GPU`

In [74]:
# Details about GPU
!nvidia-smi

/bin/bash: nvidia-smi: command not found


### Check for GPU access with PyTorch

In [75]:
# Check for GPU access with PyTorch
import torch 
torch.cuda.is_available()

False

Setup device agnostic code: 
https://pytorch.org/docs/stable/notes/cuda.html

In [76]:
# Setup device agnostic code
# Run on GPU if available, els default to CPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [77]:
# Count number of divices
torch.cuda.device_count()

0

### Putting tensors (and models) on the GPU

The rason we want our tensors/models on the GPU is because Using GPU results in faster computations.

In [78]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [79]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### Moving back tensors to the CPU

**If tensor is on GPU, can't transform it to NumPy** -> *To fix GPU tensor with NumPy issue, we can first set it on CPU*

In [80]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# Exercises

In [81]:
import torch

In [82]:
# 1. Create a random tensor with shape (7, 7).
tensor_A = torch.rand(7, 7)
tensor_A, tensor_A.shape

(tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]]),
 torch.Size([7, 7]))

In [83]:
# 2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
tensor_B = torch.rand(1, 7)

result = torch.mm(tensor_A, tensor_B.T)
result, result.shape

(tensor([[1.9625],
         [1.0950],
         [0.9967],
         [1.8910],
         [1.9205],
         [1.0674],
         [1.6949]]),
 torch.Size([7, 1]))

In [84]:
# 3. Set the random seed to 0 and do exercises 1 & 2 over again

torch.manual_seed(0)
X = torch.rand(7, 7)

torch.manual_seed(0)
Y = torch.rand(1, 7)

result = torch.mm(X, Y.T)
result, result.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [85]:
# 4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
torch.cuda.manual_seed(123)

In [86]:
# 5. Create two random tensors of shape (2, 3) and send them both to the GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

torch.manual_seed(123)
X = torch.rand(2, 3).to(device)

torch.manual_seed(123)
Y = torch.rand(2, 3).to(device)

X, Y

Device: cpu


(tensor([[0.2961, 0.5166, 0.2517],
         [0.6886, 0.0740, 0.8665]]),
 tensor([[0.2961, 0.5166, 0.2517],
         [0.6886, 0.0740, 0.8665]]))

In [87]:
# 6. Perform a matrix multiplication on the tensors you created in 5.
result = torch.mm(X, Y.T)
result, result.shape 

(tensor([[0.4179, 0.4602],
         [0.4602, 1.2304]]),
 torch.Size([2, 2]))

In [88]:
# 7. Find the maximum and minimum values of the output of 6.
minimum = result.min()
maximum = result.max()
minimum, maximum

(tensor(0.4179), tensor(1.2304))

In [89]:
# 8. Find the maximum and minimum index values of the output of 6. 
min_index = result.argmin()
max_index = result.argmax()
min_index, max_index

(tensor(0), tensor(3))

In [90]:
# 9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor 
# with all the 1 dimensions removed to be left with a tensor of shape (10). 
# Set the seed to 7 when you create it and print out the first tensor 
# and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)

random_tensor = torch.rand(1, 1, 1, 10)
print(random_tensor.shape)

new_tensor = torch.squeeze(random_tensor)
print(new_tensor.shape)

torch.Size([1, 1, 1, 10])
torch.Size([10])
